name: Deploy to cloud CI/CD PIPELINE

on:
  push:
    branches:
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with: 
          credentials_json: ${{secrets.GCP_CREDENTIALS}}
      
      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: Build docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-api/my-api .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-api/my-api
      
      - name: deploy to cloud
        run: |
          gcloud run deploy my-api \
            --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-api/my-api \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated

