name: DOCKER CI/CD PIPELINE

on:
  push:
    branches: 
      - main
  
  pull_request: 
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  docker:
    runs-on: ubuntu-latest
    
    permissions: 
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: ${{secrets.DOCKERHUB_USERNAME}}/my-api
      
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{steps.meta.outputs.tags}}
          annotations: ${{steps.meta.outputs.annotations}}
          provenance: true
          sbom: true

      - name: Run Docker Container for smoke test
        run: |
            docker run -d -p 80:80 --name my-api-container my-api || docker run -d -p 80:80 --name my-api-container ${{secrets.DOCKERHUB_USERNAME}}/my-api:latest
            sleep 5
      
      - name: run tests
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91